"""PulsePayload → data.js for the Pulse viewer."""

from __future__ import annotations

import json
from dataclasses import asdict, is_dataclass
from pathlib import Path
from typing import Any

from app.viewer.data_contract import PulsePayload


_FMT_HELPER_JS = """
window.fmt = {
  num(n) {
    if (n >= 1_000_000) return (n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1) + 'M';
    if (n >= 1_000) return (n / 1_000).toFixed(n >= 10_000 ? 0 : 1) + 'K';
    return n.toString();
  },
  pct(n, d = 1) { return n.toFixed(d) + '%'; },
  money(n) {
    if (n >= 1_000) return '$' + (n / 1_000).toFixed(1) + 'K';
    return '$' + n.toLocaleString();
  }
};
""".strip()


def serialize(payload: PulsePayload, benchmarks: dict | None = None) -> str:
    chunks: list[str] = [
        "// ============================================================",
        "// Generated by app/viewer/refresh.py — do not edit by hand.",
        "// Regenerate with: python -m app.viewer.refresh",
        "// ============================================================",
        "",
        _emit("CAMPAIGNS", payload.campaigns),
        _emit("TOP_POSTS", payload.top_posts),
        _emit("HERO_POST", payload.hero_post),
        _emit("TOP_POSTS_ORGANIC", payload.top_posts_organic),
        _emit("CHANNELS", payload.channels),
        _emit("SOURCES", payload.sources),
        _emit("SIGNALS", payload.signals),
        _emit("UB_COMPONENTS", payload.ub_components),
        _emit("EPISODES_BY_CAMPAIGN", payload.episodes_by_campaign),
        _emit("BENCHMARKS_DATA", benchmarks or {}),
        "",
        _FMT_HELPER_JS,
        "",
    ]
    return "\n\n".join(chunks)


def write_data_js(payload: PulsePayload, target: Path | str, benchmarks: dict | None = None) -> Path:
    p = Path(target)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(serialize(payload, benchmarks=benchmarks))
    tmp.replace(p)
    return p


def _emit(name: str, value: Any) -> str:
    return f"window.{name} = {json.dumps(to_js(value), indent=2, default=_fallback)};"


def to_js(obj: Any) -> Any:
    if obj is None:
        return None
    if is_dataclass(obj) and not isinstance(obj, type):
        return to_js(asdict(obj))
    if isinstance(obj, dict):
        return {_to_camel(k): to_js(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_js(x) for x in obj]
    return obj


def _to_camel(snake: str) -> str:
    if "_" not in snake:
        return snake
    parts = snake.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:] if p)


def _fallback(o: Any) -> Any:
    return str(o)
