"""PulsePayload → data.js for the Pulse viewer."""

from __future__ import annotations

import json
from dataclasses import asdict, is_dataclass
from pathlib import Path
from typing import Any

from app.viewer.data_contract import PulsePayload


_FMT_HELPER_JS = """
window.fmt = {
  num(n) {
    if (n >= 1_000_000) return (n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1) + 'M';
    if (n >= 1_000) return (n / 1_000).toFixed(n >= 10_000 ? 0 : 1) + 'K';
    return n.toString();
  },
  // Full integer with thousands separators (no K/M abbreviation).
  numFull(n) { return Math.round(Number(n) || 0).toLocaleString('en-US'); },
  pct(n, d = 1) { return n.toFixed(d) + '%'; },
  money(n) {
    if (n >= 1_000) return '$' + (n / 1_000).toFixed(1) + 'K';
    // Sub-thousand: whole dollars, no cents. Cents on spend add no useful info.
    return '$' + Math.round(n).toLocaleString();
  },
  // Full dollar amount with cents (e.g. $1,497.32). Used in episode breakdowns
  // where precise per-platform spend matters.
  moneyFull(n) {
    const v = Number(n) || 0;
    return '$' + v.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
};
""".strip()


def serialize(payload: PulsePayload, benchmarks: dict | None = None, upload_targets: dict | None = None, ms_groups: list | None = None, data_health: dict | None = None) -> str:
    # ISO-8601 UTC timestamp the dashboard sidebar footer reads via
    # `window.LAST_REFRESHED`. Captured here (not in refresh.py) so any code
    # path that emits data.js gets a fresh timestamp — including CI auto-
    # refresh runs and local debug invocations.
    from datetime import datetime, timezone
    last_refreshed = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    chunks: list[str] = [
        "// ============================================================",
        "// Generated by app/viewer/refresh.py — do not edit by hand.",
        "// Regenerate with: python -m app.viewer.refresh",
        "// ============================================================",
        "",
        f'window.LAST_REFRESHED = "{last_refreshed}";',
        "",
        _emit("CAMPAIGNS", payload.campaigns),
        _emit("TOP_POSTS", payload.top_posts),
        _emit("HERO_POST", payload.hero_post),
        _emit("TOP_POSTS_ORGANIC", payload.top_posts_organic),
        _emit("CHANNELS", payload.channels),
        _emit("SOURCES", payload.sources),
        _emit("SIGNALS", payload.signals),
        _emit("UB_COMPONENTS", payload.ub_components),
        _emit("EPISODES_BY_CAMPAIGN", payload.episodes_by_campaign),
        _emit("POSTS_BY_CAMPAIGN", payload.posts_by_campaign),
        # Per-campaign configured source files, so the upload form can target
        # the exact filename refresh.py reads (instead of guessing a name that
        # silently no-ops). See _emit's id_keyed handling.
        _emit("UPLOAD_TARGETS", upload_targets or {}),
        # MS post-group directory (id + name) for the Add-campaign group picker.
        _emit("MS_GROUPS", ms_groups or []),
        # Data Health — warnings, auto-wired uploads, orphaned files. Surfaced
        # on the dashboard so silent-failure modes become visible.
        _emit("DATA_HEALTH", data_health or {}),
        _emit("DATA_ARCHIVE", payload.data_archive),
        _emit("BENCHMARKS_DATA", benchmarks or {}),
        _emit("PORTFOLIO_CPM_BY_CHANNEL", payload.portfolio_cpm_by_channel),
        _emit("PORTFOLIO_CPM_BLEND", payload.portfolio_cpm_blend),
        # BrandX-specific benchmarks (FOS Paid Social Benchmarks workbook).
        # Used on the BrandX campaign page to show per-channel CPM deltas and
        # the blended-vs-overall comparison.
        _emit("BRANDX_BENCHMARKS", _brandx_benchmarks_payload()),
        "",
        _FMT_HELPER_JS,
        "",
    ]
    return "\n\n".join(chunks)


def _brandx_benchmarks_payload() -> dict:
    """Bundle the BrandX benchmark constants for emit to JS."""
    from app.compute.rollup import (
        BRANDX_BENCHMARK_CPM_OVERALL,
        BRANDX_BENCHMARK_CPM_BY_OBJECTIVE,
        BRANDX_BENCHMARK_CTR_OVERALL,
        BRANDX_BENCHMARK_CTR_BY_OBJECTIVE,
        BRANDX_BENCHMARK_CPM_BY_PLATFORM,
        BRANDX_BENCHMARK_VCR_OVERALL,
    )
    return {
        "cpm_overall":        BRANDX_BENCHMARK_CPM_OVERALL,
        "cpm_by_objective":   BRANDX_BENCHMARK_CPM_BY_OBJECTIVE,
        "ctr_overall":        BRANDX_BENCHMARK_CTR_OVERALL,
        "vcr_overall":        BRANDX_BENCHMARK_VCR_OVERALL,
        "ctr_by_objective":   BRANDX_BENCHMARK_CTR_BY_OBJECTIVE,
        "cpm_by_platform":    BRANDX_BENCHMARK_CPM_BY_PLATFORM,
    }


def write_data_js(payload: PulsePayload, target: Path | str, benchmarks: dict | None = None, upload_targets: dict | None = None, ms_groups: list | None = None, data_health: dict | None = None) -> Path:
    p = Path(target)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(serialize(payload, benchmarks=benchmarks, upload_targets=upload_targets, ms_groups=ms_groups, data_health=data_health))
    tmp.replace(p)
    return p


def _emit(name: str, value: Any) -> str:
    # Top-level dicts keyed by campaign ID (POSTS_BY_CAMPAIGN, EPISODES_BY_CAMPAIGN)
    # must preserve their keys as-is — c.id is the string field used for
    # lookup on the JSX side, and converting `etrade_brandx` to `etradeBrandx`
    # breaks `(window.POSTS_BY_CAMPAIGN || {})[c.id]`.
    id_keyed = name in ("POSTS_BY_CAMPAIGN", "EPISODES_BY_CAMPAIGN", "UPLOAD_TARGETS")
    return f"window.{name} = {json.dumps(to_js(value, preserve_top_keys=id_keyed), indent=2, default=_fallback)};"


def to_js(obj: Any, preserve_top_keys: bool = False) -> Any:
    if obj is None:
        return None
    if is_dataclass(obj) and not isinstance(obj, type):
        return to_js(asdict(obj))
    if isinstance(obj, dict):
        # Preserve top-level keys for ID-indexed maps so c.id lookups work.
        # Nested dicts (the values) still get the snake → camel conversion
        # since they're dataclass field-name dicts.
        if preserve_top_keys:
            return {k: to_js(v) for k, v in obj.items()}
        return {_to_camel(k): to_js(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_js(x) for x in obj]
    return obj


def _to_camel(snake: str) -> str:
    if "_" not in snake:
        return snake
    parts = snake.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:] if p)


def _fallback(o: Any) -> Any:
    return str(o)
