/* global React, CAMPAIGNS, DATA_ARCHIVE, fmt, Ic, PageHead */
// ============================================================
// DATA ARCHIVE — audit trail of every source file the dashboard
// reads. One row per (campaign × source file). Lets the operator
// confirm which exports are flowing into which campaign, when each
// file was last updated, and how many parsed posts came from it.
//
// All data shown here is generated by app/viewer/refresh.py's
// _build_data_archive(), exposed on window.DATA_ARCHIVE.
// ============================================================

function DataArchivePage() {
  const archive = (window.DATA_ARCHIVE || []);

  // Allow filtering by campaign + source kind
  const [campaignFilter, setCampaignFilter] = React.useState('all');
  const [sourceFilter,   setSourceFilter]   = React.useState('all');
  const [query,          setQuery]          = React.useState('');

  const filtered = archive.filter(r => {
    if (campaignFilter !== 'all' && r.campaignId !== campaignFilter) return false;
    if (sourceFilter   !== 'all' && r.sourceKind  !== sourceFilter)  return false;
    if (query && !r.filename.toLowerCase().includes(query.toLowerCase()) &&
        !r.partner.toLowerCase().includes(query.toLowerCase())) return false;
    return true;
  });

  const sourceKinds = Array.from(new Set(archive.map(r => r.sourceKind)));

  // Stats for the header
  const totalFiles = archive.length;
  const missing = archive.filter(r => !r.exists).length;
  const totalPosts = archive.reduce((s, r) => s + (r.postsContributed || 0), 0);

  return (
    <>
      <PageHead
        overline={`Sponsored campaigns · ${new Date().toLocaleString('en-US', { month: 'long', year: 'numeric' })}`}
        title="Data"
        italic="archive"
        sub="Every source file currently feeding the dashboard. Use this to audit what's loaded, when it was last refreshed, and how many parsed posts came from each file."
      />

      {/* STATS STRIP */}
      <div style={{display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap:14, marginBottom:24}}>
        <StatCard label="Source files loaded" value={totalFiles}/>
        <StatCard label="Campaigns covered"   value={CAMPAIGNS.length}/>
        <StatCard label="Posts attributed"    value={fmt.numFull(totalPosts)}/>
        <StatCard label="Missing files"       value={missing} tone={missing > 0 ? 'warn' : 'ok'}/>
      </div>

      {/* OPTIONAL: GOOGLE SHEET LINK */}
      <div className="card" style={{
        padding:'18px 22px', marginBottom:24,
        background:'rgba(36,28,23,0.04)', border:'1px dashed var(--line-2)'
      }}>
        <div style={{display:'flex', justifyContent:'space-between', alignItems:'center', gap:20}}>
          <div>
            <div style={{fontSize:13, fontWeight:600, letterSpacing:'-0.01em', marginBottom:4}}>
              Full data backup
            </div>
            <div style={{fontSize:12, color:'var(--ink-2)', lineHeight:1.5}}>
              For long-term safekeeping, mirror each export here to a shared Google Sheet (one tab per campaign × source). The dashboard reads from <code>tests/fixtures/</code>; the Sheet is your archive of record.
            </div>
          </div>
          <a href="#" onClick={(e) => e.preventDefault()} className="btn btn-acc" style={{whiteSpace:'nowrap'}}>
            Open archive sheet (TBD)
          </a>
        </div>
      </div>

      {/* FILTERS */}
      <div style={{
        display:'flex', gap:10, marginBottom:14, alignItems:'center', flexWrap:'wrap'
      }}>
        <select
          value={campaignFilter} onChange={e => setCampaignFilter(e.target.value)}
          style={filterStyle}>
          <option value="all">All campaigns</option>
          {CAMPAIGNS.map(c => (
            <option key={c.id} value={c.id}>{c.partner} — {c.series}</option>
          ))}
        </select>
        <select
          value={sourceFilter} onChange={e => setSourceFilter(e.target.value)}
          style={filterStyle}>
          <option value="all">All sources</option>
          {sourceKinds.map(k => <option key={k} value={k}>{k}</option>)}
        </select>
        <div style={{display:'flex', alignItems:'center', gap:6,
          border:'1px solid var(--line)', borderRadius:6, padding:'0 10px',
          background:'var(--bg)', flex:'1 1 220px', minWidth:200, maxWidth:360
        }}>
          <Ic.search/>
          <input
            value={query} onChange={e => setQuery(e.target.value)}
            placeholder="Search filename or partner"
            style={{
              flex:1, border:'none', outline:'none', padding:'9px 0',
              fontSize:13, fontFamily:'inherit', background:'transparent'
            }}/>
        </div>
        <div style={{fontSize:11, color:'var(--ink-3)', marginLeft:'auto', fontFamily:'var(--mono)'}}>
          {filtered.length} / {archive.length} files
        </div>
      </div>

      {/* TABLE */}
      <div className="card" style={{padding:0, overflow:'hidden'}}>
        <div style={{
          display:'grid',
          gridTemplateColumns:'180px 160px 1fr 90px 110px 90px 80px',
          gap:14, padding:'14px 22px',
          background:'var(--bg-soft)', borderBottom:'1px solid var(--line)',
          fontSize:10, fontFamily:'var(--mono)', color:'var(--ink-3)',
          letterSpacing:'0.1em', fontWeight:600, textTransform:'uppercase'
        }}>
          <div>Campaign</div>
          <div>Source</div>
          <div>Filename</div>
          <div style={{textAlign:'right'}}>Posts</div>
          <div style={{textAlign:'right'}}>Last modified</div>
          <div style={{textAlign:'right'}}>Size</div>
          <div style={{textAlign:'right'}}>Status</div>
        </div>

        {filtered.length === 0 && (
          <div style={{padding:48, textAlign:'center', color:'var(--ink-3)', fontSize:13}}>
            No source files match the current filter.
          </div>
        )}

        {filtered.map((r, i) => (
          <div key={i} style={{
            display:'grid',
            gridTemplateColumns:'180px 160px 1fr 90px 110px 90px 80px',
            gap:14, padding:'14px 22px', alignItems:'center',
            borderBottom: i < filtered.length - 1 ? '1px solid var(--line)' : 'none',
            fontSize:13, background: r.exists ? 'var(--bg)' : 'rgba(184,57,43,0.04)'
          }}>
            <div style={{minWidth:0, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap'}}>
              <div style={{fontWeight:500}}>{r.partner}</div>
              <div style={{fontSize:10, color:'var(--ink-3)', fontFamily:'var(--mono)', letterSpacing:'0.04em'}}>{r.campaignId}</div>
            </div>
            <div style={{fontSize:12, color:'var(--ink-2)'}}>{r.sourceLabel}</div>
            <div style={{
              fontFamily:'var(--mono)', fontSize:12, color:'var(--ink-2)',
              minWidth:0, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap'
            }}>{r.filename}</div>
            <div style={{textAlign:'right', fontVariantNumeric:'tabular-nums', fontWeight:500}}>
              {r.postsContributed ? fmt.numFull(r.postsContributed) : '—'}
            </div>
            <div style={{textAlign:'right', fontVariantNumeric:'tabular-nums', fontSize:12, color:'var(--ink-3)', fontFamily:'var(--mono)'}}>
              {r.lastModified}
            </div>
            <div style={{textAlign:'right', fontVariantNumeric:'tabular-nums', fontSize:12, color:'var(--ink-3)'}}>
              {r.fileSizeKb !== null ? `${fmt.numFull(r.fileSizeKb)} KB` : '—'}
            </div>
            <div style={{textAlign:'right'}}>
              {r.exists ? (
                <span style={{
                  fontFamily:'var(--mono)', fontSize:10, letterSpacing:'0.06em', fontWeight:600,
                  padding:'3px 8px', borderRadius:3,
                  background:'rgba(143,199,102,0.18)', color:'#2f7a3f'
                }}>OK</span>
              ) : (
                <span style={{
                  fontFamily:'var(--mono)', fontSize:10, letterSpacing:'0.06em', fontWeight:600,
                  padding:'3px 8px', borderRadius:3,
                  background:'rgba(184,57,43,0.18)', color:'#b8392b'
                }}>MISSING</span>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* HOW THIS WORKS */}
      <div className="sec" style={{marginTop:32}}>
        <div className="card" style={{padding:24}}>
          <div className="card-title-serif" style={{fontSize:18, marginBottom:12}}>How <em>this works</em></div>
          <div style={{fontSize:13, color:'var(--ink-2)', lineHeight:1.65, display:'flex', flexDirection:'column', gap:10}}>
            <p>This page shows the full source manifest behind every number in the dashboard. Each row is one export file referenced in <code>config/campaigns.yaml</code>. We surface where it lives, when it was last updated, and how many parsed posts came from it.</p>
            <p><strong>Missing files</strong> (red badge) mean the YAML references a file that's not in <code>tests/fixtures/</code> — fix by either dropping the file or removing the reference.</p>
            <p><strong>Posts column</strong> shows posts from this campaign that match the source's parser. Because we don't tag posts by individual filename, this is grouped per source kind (e.g., all Measure Studio rows for E*TRADE are counted together, not split by which MS export they came from).</p>
            <p><strong>Long-term storage:</strong> the Google Sheet linked above is the system of record. Mirror exports there before processing so you always have a clean copy independent of the dashboard's working files.</p>
          </div>
        </div>
      </div>
    </>
  );
}

function StatCard({ label, value, tone = 'neutral' }) {
  const toneColor = tone === 'warn' ? '#b8392b' : tone === 'ok' ? '#2f7a3f' : 'var(--ink)';
  return (
    <div className="card" style={{padding:'18px 22px'}}>
      <div style={{fontSize:10, color:'var(--ink-3)', letterSpacing:'0.1em', textTransform:'uppercase', fontWeight:600, marginBottom:8}}>{label}</div>
      <div style={{fontFamily:'var(--serif)', fontSize:32, fontWeight:300, letterSpacing:'-0.01em', color:toneColor}}>{value}</div>
    </div>
  );
}

const filterStyle = {
  background:'var(--bg)', border:'1px solid var(--line)', borderRadius:6,
  padding:'9px 12px', fontSize:13, fontFamily:'inherit', color:'var(--ink)', outline:'none',
};

window.DataArchivePage = DataArchivePage;
