// ============================================================

// Generated by app/viewer/refresh.py — do not edit by hand.

// Regenerate with: python -m app.viewer.refresh

// ============================================================



window.CAMPAIGNS = [
  {
    "id": "usbank",
    "partner": "US Bank",
    "series": "NFL Draft",
    "seriesItalic": "Draft",
    "type": "social",
    "flight": "Apr 21 \u2014 May 15, 2026",
    "elapsedPct": 95.8,
    "daysLeft": 1,
    "status": "Behind Pace",
    "statusKind": "danger",
    "impressions": {
      "delivered": 3728374,
      "goal": 14000000
    },
    "budget": {
      "delivered": 17064.84,
      "goal": 31375.0
    },
    "color": "ft-4",
    "leadFormat": "Made for Social",
    "topChannel": "Instagram",
    "er": 56.5,
    "cpm": 4.58,
    "episodes": 0,
    "posts": 10,
    "blurb": "3 social components, 38 posts live across IG, FB, X, LinkedIn & YouTube Shorts. Delivered 103.6% of impression goal on 98.8% of budget.",
    "benchmarkCategory": "Social Coverage Partner",
    "lifecycle": "wrapped",
    "channels": [
      {
        "name": "Instagram",
        "italic": "gram",
        "impressions": 2791202,
        "eng": 1478285,
        "er": 52.96,
        "cpm": 4.5,
        "color": "#E4405F",
        "delta": 1500.1,
        "bench": {
          "er": 3.31,
          "cpm": 5.1
        },
        "organicImpressions": 0
      },
      {
        "name": "Facebook",
        "italic": "book",
        "impressions": 937172,
        "eng": 629425,
        "er": 67.16,
        "cpm": 4.82,
        "color": "#1877F2",
        "delta": 4289.7,
        "bench": {
          "er": 1.53,
          "cpm": 4.8
        },
        "organicImpressions": 0
      }
    ],
    "topPosts": [
      {
        "id": "US Bank_NFL Draft_Red Carpet_Video 1",
        "rank": 1,
        "partner": "US Bank",
        "platform": "Instagram",
        "format": "Feed video",
        "quote": "Cars, homes, watches\u2026",
        "er": 76.83,
        "eng": 336080,
        "reach": 437411,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_The Come Up_Video 4 (FB)",
        "rank": 2,
        "partner": "US Bank",
        "platform": "Facebook",
        "format": "Feed video",
        "quote": "Downs",
        "er": 68.95,
        "eng": 155485,
        "reach": 206515,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_The Come Up_Video 3 (FB)",
        "rank": 3,
        "partner": "US Bank",
        "platform": "Facebook",
        "format": "Feed video",
        "quote": "Tate",
        "er": 67.84,
        "eng": 156334,
        "reach": 217470,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_The Come Up_Video 2 (FB)",
        "rank": 4,
        "partner": "US Bank",
        "platform": "Facebook",
        "format": "Feed video",
        "quote": "Mendoza",
        "er": 66.54,
        "eng": 162580,
        "reach": 228241,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_The Come Up_Video 2 (IG)",
        "rank": 5,
        "partner": "US Bank",
        "platform": "Instagram",
        "format": "Feed video",
        "quote": "Mendoza",
        "er": 66.02,
        "eng": 310405,
        "reach": 464655,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_The Come Up_Video 1 (FB)",
        "rank": 6,
        "partner": "US Bank",
        "platform": "Facebook",
        "format": "Feed video",
        "quote": "Mauigoa",
        "er": 65.45,
        "eng": 155026,
        "reach": 218245,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_The Come Up_Video 4 (IG)",
        "rank": 7,
        "partner": "US Bank",
        "platform": "Instagram",
        "format": "Feed video",
        "quote": "Downs",
        "er": 63.05,
        "eng": 272125,
        "reach": 390982,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_The Come Up_Video 1 (IG)",
        "rank": 8,
        "partner": "US Bank",
        "platform": "Instagram",
        "format": "Feed video",
        "quote": "Mauigoa",
        "er": 61.06,
        "eng": 259516,
        "reach": 367160,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_The Come Up_Video 3 (IG)",
        "rank": 9,
        "partner": "US Bank",
        "platform": "Instagram",
        "format": "Feed video",
        "quote": "Tate",
        "er": 60.11,
        "eng": 234622,
        "reach": 361026,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      },
      {
        "id": "US Bank_NFL Draft_Red Carpet_Video 2",
        "rank": 10,
        "partner": "US Bank",
        "platform": "Instagram",
        "format": "Feed video",
        "quote": "US Bank_NFL Draft_Red Carpet_Video 2",
        "er": 10.29,
        "eng": 65537,
        "reach": 523547,
        "organic": 0,
        "metric": "er",
        "insight": "",
        "url": null
      }
    ],
    "topPostsOrganic": [],
    "callouts": [
      {
        "tag": "WIN",
        "kind": "pos",
        "headline": "Facebook post at 69.0% ER \u2014 45.1\u00d7 the benchmark.",
        "body": "\"Downs\" \u2014 207K reach, 155K engagements (0% organic). Strongest single asset on the campaign and well clear of the Facebook benchmark. Feature it in the partner update.",
        "meta": "US Bank \u00b7 Facebook"
      },
      {
        "tag": "WATCH",
        "kind": "warn",
        "headline": "72% behind pacing with 1 days left.",
        "body": "10.3M impressions still needed to hit the 14.0M goal. Needs immediate optimization \u2014 reallocate budget to the highest-efficiency channels or extend the flight before launch slots disappear.",
        "meta": "US Bank \u00b7 Pacing"
      }
    ]
  }
];

window.TOP_POSTS = [
  {
    "id": "US Bank_NFL Draft_Red Carpet_Video 1",
    "rank": 1,
    "partner": "US Bank",
    "platform": "Instagram",
    "format": "Feed video",
    "quote": "Cars, homes, watches\u2026",
    "er": 76.83,
    "eng": 336080,
    "reach": 437411,
    "organic": 0,
    "metric": "er",
    "insight": "",
    "url": null
  },
  {
    "id": "US Bank_NFL Draft_The Come Up_Video 4 (FB)",
    "rank": 2,
    "partner": "US Bank",
    "platform": "Facebook",
    "format": "Feed video",
    "quote": "Downs",
    "er": 68.95,
    "eng": 155485,
    "reach": 206515,
    "organic": 0,
    "metric": "er",
    "insight": "",
    "url": null
  },
  {
    "id": "US Bank_NFL Draft_The Come Up_Video 3 (FB)",
    "rank": 3,
    "partner": "US Bank",
    "platform": "Facebook",
    "format": "Feed video",
    "quote": "Tate",
    "er": 67.84,
    "eng": 156334,
    "reach": 217470,
    "organic": 0,
    "metric": "er",
    "insight": "",
    "url": null
  },
  {
    "id": "US Bank_NFL Draft_The Come Up_Video 2 (FB)",
    "rank": 4,
    "partner": "US Bank",
    "platform": "Facebook",
    "format": "Feed video",
    "quote": "Mendoza",
    "er": 66.54,
    "eng": 162580,
    "reach": 228241,
    "organic": 0,
    "metric": "er",
    "insight": "",
    "url": null
  },
  {
    "id": "US Bank_NFL Draft_The Come Up_Video 2 (IG)",
    "rank": 5,
    "partner": "US Bank",
    "platform": "Instagram",
    "format": "Feed video",
    "quote": "Mendoza",
    "er": 66.02,
    "eng": 310405,
    "reach": 464655,
    "organic": 0,
    "metric": "er",
    "insight": "",
    "url": null
  },
  {
    "id": "US Bank_NFL Draft_The Come Up_Video 1 (FB)",
    "rank": 6,
    "partner": "US Bank",
    "platform": "Facebook",
    "format": "Feed video",
    "quote": "Mauigoa",
    "er": 65.45,
    "eng": 155026,
    "reach": 218245,
    "organic": 0,
    "metric": "er",
    "insight": "",
    "url": null
  },
  {
    "id": "US Bank_NFL Draft_The Come Up_Video 4 (IG)",
    "rank": 7,
    "partner": "US Bank",
    "platform": "Instagram",
    "format": "Feed video",
    "quote": "Downs",
    "er": 63.05,
    "eng": 272125,
    "reach": 390982,
    "organic": 0,
    "metric": "er",
    "insight": "",
    "url": null
  },
  {
    "id": "US Bank_NFL Draft_The Come Up_Video 1 (IG)",
    "rank": 8,
    "partner": "US Bank",
    "platform": "Instagram",
    "format": "Feed video",
    "quote": "Mauigoa",
    "er": 61.06,
    "eng": 259516,
    "reach": 367160,
    "organic": 0,
    "metric": "er",
    "insight": "",
    "url": null
  }
];

window.HERO_POST = {
  "partner": "US Bank",
  "platform": "Instagram",
  "format": "0% organic feed video",
  "quote": "Cars, homes, watches\u2026",
  "attribution": "US Bank \u2014 top performer",
  "er": "76.83%",
  "eng": "336,080",
  "reach": "437,411",
  "organic": "0%"
};

window.TOP_POSTS_ORGANIC = [];

window.CHANNELS = [
  {
    "name": "Instagram",
    "italic": "gram",
    "impressions": 2791202,
    "eng": 1478285,
    "er": 52.96,
    "cpm": 4.5,
    "color": "#E4405F",
    "delta": 1500.1,
    "bench": {
      "er": 3.31,
      "cpm": 5.1
    },
    "organicImpressions": 0
  },
  {
    "name": "Facebook",
    "italic": "book",
    "impressions": 937172,
    "eng": 629425,
    "er": 67.16,
    "cpm": 4.82,
    "color": "#1877F2",
    "delta": 4289.7,
    "bench": {
      "er": 1.53,
      "cpm": 4.8
    },
    "organicImpressions": 0
  }
];

window.SOURCES = [
  {
    "name": "Measure Studio",
    "date": "May 5, 2026",
    "stale": false
  },
  {
    "name": "Google Ads",
    "date": "May 5, 2026",
    "stale": false
  },
  {
    "name": "X Ads Manager",
    "date": "May 5, 2026",
    "stale": false
  },
  {
    "name": "Meta Business",
    "date": "May 4, 2026",
    "stale": false
  },
  {
    "name": "TikTok Ads",
    "date": "May 1, 2026",
    "stale": true
  },
  {
    "name": "YouTube Studio",
    "date": "May 5, 2026",
    "stale": false
  }
];

window.SIGNALS = [
  {
    "kind": "opportunity",
    "title": "LinkedIn = free engagement",
    "body": "TastyTrade, ADP, and E*TRADE all hit 4%+ ER on LinkedIn at $0 spend. Default-include in every content package."
  },
  {
    "kind": "win",
    "title": "TikTok is your zero-cost reach engine",
    "body": "TastyTrade TikTok delivered 592K views on $267 in spend \u2014 228% of contracted impressions. Should be a default channel for every package."
  },
  {
    "kind": "watch",
    "title": "E*TRADE pacing watch",
    "body": "72% of flight elapsed but only 11% of impressions delivered. Mark Cuban episode launching this week should close the gap."
  }
];

window.UB_COMPONENTS = [
  {
    "id": "comeup",
    "n": "01",
    "title": "The Come Up",
    "italic": "Up",
    "sub": "4 Athlete Stories \u00d7 5 Platforms \u00b7 20 Posts Live",
    "status": "Goal Exceeded",
    "statusKind": "on",
    "color": "var(--orange)",
    "fg": "var(--liquorice)",
    "accent": "ft-1",
    "impressions": {
      "delivered": 8410825,
      "goal": 8000000
    },
    "budget": {
      "delivered": 22743,
      "goal": 16875
    },
    "engagements": 306409,
    "er": 3.6,
    "posts": 20,
    "blurb": "X paid drove 4.65M impressions at $1.54 CPM \u2014 the dominant reach driver. Meta delivered 2.65M IG+FB. YT Shorts 25.0% blended ER.",
    "budgetNote": "Budget reallocated from Native Social to support paid amplification after CPMs ran elevated during the busy draft window.",
    "platforms": [
      {
        "name": "Instagram",
        "posts": 4,
        "organic": 50803,
        "paid": 1717115,
        "total": 1767918,
        "eng": 139158,
        "er": 7.9,
        "spend": 8664.43,
        "est": 7102,
        "pct": 122.0
      },
      {
        "name": "Facebook",
        "posts": 4,
        "organic": 35023,
        "paid": 936646,
        "total": 971669,
        "eng": 16177,
        "er": 1.7,
        "spend": 4512.05,
        "est": 3721,
        "pct": 121.3
      },
      {
        "name": "X",
        "posts": 4,
        "organic": 253827,
        "paid": 4653038,
        "total": 4906865,
        "eng": 4938,
        "er": 0.1,
        "spend": 7180.0,
        "est": 2500,
        "pct": 287.2
      },
      {
        "name": "LinkedIn",
        "posts": 4,
        "organic": 187787,
        "paid": null,
        "total": 187787,
        "eng": 2046,
        "er": 1.1,
        "spend": 0,
        "est": 0,
        "pct": null
      },
      {
        "name": "YouTube Shorts",
        "posts": 4,
        "organic": 179914,
        "paid": 396672,
        "total": 576586,
        "eng": 144090,
        "er": 25.0,
        "spend": 2386.88,
        "est": 3592,
        "pct": 66.5
      }
    ],
    "stories": [
      {
        "name": "Mauigoa",
        "kind": "Non-Collab",
        "published": "4/22",
        "sub": "OL \u00b7 American Samoa \u2192 5-Star IMG Prospect",
        "reach": 2747650,
        "eng": 76932,
        "spend": 6235,
        "rows": [
          {
            "plat": "Instagram",
            "dist": "organic+paid",
            "impr": 484628,
            "eng": 39924,
            "er": 8.2,
            "spend": 2163.3
          },
          {
            "plat": "Facebook",
            "dist": "organic+paid",
            "impr": 271956,
            "eng": 5417,
            "er": 2.0,
            "spend": 1129.95
          },
          {
            "plat": "X",
            "dist": "organic+paid",
            "impr": 1775698,
            "eng": 2244,
            "er": 0.13,
            "spend": 2345.0
          },
          {
            "plat": "LinkedIn",
            "dist": "organic",
            "impr": 84358,
            "eng": 733,
            "er": 0.9,
            "spend": 0
          },
          {
            "plat": "YouTube Shorts",
            "dist": "organic+paid",
            "impr": 131010,
            "eng": 28614,
            "er": 21.8,
            "spend": 596.82
          }
        ],
        "highlight": "Highest reach story (2.75M). X paid delivered 1.64M at $1.43 CPM. IG at 8.2% ER. Non-collab leader."
      },
      {
        "name": "Tate",
        "kind": "Non-Collab",
        "published": "4/23",
        "sub": "WR \u00b7 Tragedy \u2192 NFL Draft",
        "reach": 1974102,
        "eng": 92016,
        "spend": 5537,
        "rows": [
          {
            "plat": "Instagram",
            "dist": "organic+paid",
            "impr": 446436,
            "eng": 35221,
            "er": 7.9,
            "spend": 2165.46
          },
          {
            "plat": "Facebook",
            "dist": "organic+paid",
            "impr": 229036,
            "eng": 5251,
            "er": 2.3,
            "spend": 1129.98
          },
          {
            "plat": "X",
            "dist": "organic+paid",
            "impr": 1087225,
            "eng": 770,
            "er": 0.07,
            "spend": 1645.0
          },
          {
            "plat": "LinkedIn",
            "dist": "organic",
            "impr": 17061,
            "eng": 85,
            "er": 0.5,
            "spend": 0
          },
          {
            "plat": "YouTube Shorts",
            "dist": "organic+paid",
            "impr": 194344,
            "eng": 50689,
            "er": 26.1,
            "spend": 596.17
          }
        ],
        "highlight": "Highest engagement story (92K). YT Shorts 26.1% ER. IG 7.9%. Strongest emotional resonance."
      },
      {
        "name": "Downs",
        "kind": "Collab",
        "published": "4/23",
        "sub": "DB \u00b7 Family of Pros \u2192 Carving His Own Name",
        "reach": 1919294,
        "eng": 52634,
        "spend": 5542,
        "rows": [
          {
            "plat": "Instagram",
            "dist": "organic+paid",
            "impr": 401309,
            "eng": 11778,
            "er": 2.9,
            "spend": 2167.7
          },
          {
            "plat": "Facebook",
            "dist": "organic+paid",
            "impr": 232187,
            "eng": 2300,
            "er": 1.0,
            "spend": 1129.98
          },
          {
            "plat": "X",
            "dist": "organic+paid",
            "impr": 1106334,
            "eng": 725,
            "er": 0.07,
            "spend": 1645.0
          },
          {
            "plat": "LinkedIn",
            "dist": "organic",
            "impr": 13948,
            "eng": 44,
            "er": 0.3,
            "spend": 0
          },
          {
            "plat": "YouTube Shorts",
            "dist": "organic+paid",
            "impr": 165516,
            "eng": 37787,
            "er": 22.8,
            "spend": 599.51
          }
        ],
        "highlight": "X paid at 1.1M impr. YT Shorts 22.8% ER. IG ER lower at 2.9% \u2014 collab format underperforming here."
      },
      {
        "name": "Mendoza",
        "kind": "Collab",
        "published": "4/21",
        "sub": "QB \u00b7 Overlooked \u2192 Probable No. 1 Pick",
        "reach": 1769779,
        "eng": 84827,
        "spend": 5429,
        "rows": [
          {
            "plat": "Instagram",
            "dist": "organic+paid",
            "impr": 435545,
            "eng": 52235,
            "er": 12.0,
            "spend": 2167.97
          },
          {
            "plat": "Facebook",
            "dist": "organic+paid",
            "impr": 238490,
            "eng": 3209,
            "er": 1.3,
            "spend": 1122.14
          },
          {
            "plat": "X",
            "dist": "organic+paid",
            "impr": 937608,
            "eng": 1199,
            "er": 0.13,
            "spend": 1545.0
          },
          {
            "plat": "LinkedIn",
            "dist": "organic",
            "impr": 72420,
            "eng": 1184,
            "er": 1.6,
            "spend": 0
          },
          {
            "plat": "YouTube Shorts",
            "dist": "organic+paid",
            "impr": 85716,
            "eng": 27000,
            "er": 31.5,
            "spend": 594.38
          }
        ],
        "highlight": "Highest IG ER (12.0% \u2014 52K eng). YT Shorts 31.5% ER. Strongest collab story by engagement quality."
      }
    ],
    "callouts": [
      {
        "kind": "pos",
        "tag": "GOAL EXCEEDED",
        "headline": "8.41M impressions delivered against 8M target (105.1%).",
        "body": "All 4 stories above 1.7M. X paid drove 4.65M (55%); Meta delivered 2.65M IG+FB. 3.6% blended ER, 306K total engagements."
      },
      {
        "kind": "warn",
        "tag": "BUDGET OVERSPEND",
        "headline": "$22,743 spent of $16,875 contracted (134.8%). X at 287% of allocation.",
        "body": "X spent $7,180 vs $2,500 allocated. IG at 122%, FB 121%. YT Shorts only platform under at 66.5%. Flag X overspend & 0.10% ER for future learnings."
      },
      {
        "kind": "pos",
        "tag": "ENGAGEMENT LEADER",
        "headline": "Tate is the engagement leader (92K) despite being last to publish.",
        "body": "Driven by YT Shorts (51K eng, 26.1% ER) and IG (35K eng, 7.9% ER). Mauigoa leads reach at 2.75M via X paid. Both formats \u2014 collab and non-collab \u2014 worked for different reasons."
      }
    ]
  },
  {
    "id": "native",
    "n": "02",
    "title": "Native Social Coverage",
    "italic": "Coverage",
    "sub": "Draft Day editorial \u00b7 10 Posts Live \u00b7 4 Platforms",
    "status": "In Flight",
    "statusKind": "watch",
    "color": "var(--pear)",
    "fg": "var(--liquorice)",
    "accent": "ft-4",
    "impressions": {
      "delivered": 1964772,
      "goal": 2500000
    },
    "budget": {
      "delivered": 0,
      "goal": 6000
    },
    "engagements": 72579,
    "er": 3.7,
    "posts": 10,
    "blurb": "Organic momentum strong \u2014 78.6% of goal reached with $0 paid spend. IG is the powerhouse at 1.41M (72%, 4.0% ER). LinkedIn at 3.95% ER on 382K impr.",
    "platforms": [
      {
        "name": "Instagram",
        "posts": 3,
        "organic": 1412517,
        "paid": 0,
        "total": 1412517,
        "eng": 56796,
        "er": 4.02,
        "spend": 0,
        "est": null,
        "pct": null
      },
      {
        "name": "Facebook",
        "posts": 1,
        "organic": 135356,
        "paid": 0,
        "total": 135356,
        "eng": 254,
        "er": 0.19,
        "spend": 0,
        "est": null,
        "pct": null
      },
      {
        "name": "LinkedIn",
        "posts": 3,
        "organic": 382247,
        "paid": 0,
        "total": 382247,
        "eng": 15087,
        "er": 3.95,
        "spend": 0,
        "est": null,
        "pct": null
      },
      {
        "name": "X",
        "posts": 3,
        "organic": 34652,
        "paid": 0,
        "total": 34652,
        "eng": 442,
        "er": 1.28,
        "spend": 0,
        "est": null,
        "pct": null
      }
    ],
    "callouts": [
      {
        "kind": "pos",
        "tag": "ORGANIC MOMENTUM",
        "headline": "1.96M impressions from 10 posts on $0 spend (78.6% of 2.5M goal).",
        "body": "Instagram is the powerhouse \u2014 1.41M impr, 72% of total, 4.0% ER. LinkedIn delivering strong engagement at 3.95% ER. Continued organic posting through May 15 should close the 536K gap without deploying paid."
      }
    ]
  },
  {
    "id": "redcarpet",
    "n": "03",
    "title": "Red Carpet with Baker Machado",
    "italic": "Machado",
    "sub": "NFL Draft Red Carpet interviews \u00b7 2 Videos \u00b7 8 Posts Live",
    "status": "Goal Exceeded",
    "statusKind": "on",
    "color": "var(--flame)",
    "fg": "var(--paper)",
    "accent": "ft-6",
    "impressions": {
      "delivered": 4130182,
      "goal": 3500000
    },
    "budget": {
      "delivered": 8242,
      "goal": 8500
    },
    "engagements": 195662,
    "er": 4.7,
    "posts": 8,
    "blurb": "Red Carpet smashed its 3.5M goal with 4.13M delivered at 97% budget. X top reach (1.78M). YT Shorts strongest engagement (167K eng, 19.1% ER).",
    "budgetNote": "Budget reallocated from Native Social Coverage to support paid amplification after organic came in lower than expected.",
    "videos": [
      {
        "name": "Video 1",
        "dist": "Organic + Paid",
        "quote": "\"Cars, homes, watches\u2026\"",
        "rows": [
          {
            "plat": "Instagram",
            "dist": "organic+paid",
            "impr": 774249,
            "eng": 25546,
            "er": 3.3,
            "spend": 1887.11
          },
          {
            "plat": "Facebook",
            "dist": "organic",
            "impr": 6327,
            "eng": 51,
            "er": 0.8,
            "spend": 0
          },
          {
            "plat": "X",
            "dist": "organic+paid",
            "impr": 864430,
            "eng": 1454,
            "er": 0.17,
            "spend": 861.24
          },
          {
            "plat": "LinkedIn",
            "dist": "organic",
            "impr": 59423,
            "eng": 294,
            "er": 0.5,
            "spend": 0
          },
          {
            "plat": "YouTube Shorts",
            "dist": "organic+paid",
            "impr": 327627,
            "eng": 114309,
            "er": 34.9,
            "spend": 1300.28
          }
        ],
        "subtotal": {
          "impr": 2032056,
          "eng": 141654,
          "er": 7.0,
          "spend": 4048.63
        }
      },
      {
        "name": "Video 2",
        "dist": "Paid Only (Dark)",
        "quote": "\"Best financial advice\u2026\"",
        "rows": [
          {
            "plat": "Instagram",
            "dist": "paid",
            "impr": 636674,
            "eng": 497,
            "er": 0.08,
            "spend": 1999.96
          },
          {
            "plat": "X",
            "dist": "paid",
            "impr": 916140,
            "eng": 712,
            "er": 0.08,
            "spend": 900.0
          },
          {
            "plat": "YouTube Shorts",
            "dist": "paid",
            "impr": 545312,
            "eng": 52799,
            "er": 9.7,
            "spend": 1293.86
          }
        ],
        "subtotal": {
          "impr": 2098126,
          "eng": 54008,
          "er": 2.6,
          "spend": 4193.82
        }
      }
    ],
    "callouts": [
      {
        "kind": "pos",
        "tag": "GOAL EXCEEDED",
        "headline": "4.13M impressions on $8,242 (118% of 3.5M target, 97% budget).",
        "body": "X top reach driver (1.78M, 43%). YT Shorts strongest engagement at 167K / 19.1% ER. IG organic drove 336K views with 25.5K engagements. Blended CPM $2.00."
      }
    ]
  }
];

window.EPISODES_BY_CAMPAIGN = {
  "usbank": []
};

window.POSTS_BY_CAMPAIGN = {
  "usbank": [
    {
      "title": "US Bank_NFL Draft_Red Carpet_Video 2",
      "platform": "Instagram",
      "distKind": "paid",
      "impr": 636675,
      "paidImpr": 636675,
      "orgImpr": 0,
      "eng": 65537,
      "er": 10.29,
      "spend": 1999.96,
      "url": null
    },
    {
      "title": "Mendoza",
      "platform": "Instagram",
      "distKind": "paid",
      "impr": 470158,
      "paidImpr": 470158,
      "orgImpr": 0,
      "eng": 310405,
      "er": 66.02,
      "spend": 2163.3,
      "url": null
    },
    {
      "title": "Cars, homes, watches\u2026",
      "platform": "Instagram",
      "distKind": "paid",
      "impr": 437411,
      "paidImpr": 437411,
      "orgImpr": 0,
      "eng": 336080,
      "er": 76.83,
      "spend": 1887.12,
      "url": null
    },
    {
      "title": "Downs",
      "platform": "Instagram",
      "distKind": "paid",
      "impr": 431607,
      "paidImpr": 431607,
      "orgImpr": 0,
      "eng": 272125,
      "er": 63.05,
      "spend": 2165.46,
      "url": null
    },
    {
      "title": "Mauigoa",
      "platform": "Instagram",
      "distKind": "paid",
      "impr": 425037,
      "paidImpr": 425037,
      "orgImpr": 0,
      "eng": 259516,
      "er": 61.06,
      "spend": 2167.97,
      "url": null
    },
    {
      "title": "Tate",
      "platform": "Instagram",
      "distKind": "paid",
      "impr": 390314,
      "paidImpr": 390314,
      "orgImpr": 0,
      "eng": 234622,
      "er": 60.11,
      "spend": 2167.7,
      "url": null
    },
    {
      "title": "Mendoza",
      "platform": "Facebook",
      "distKind": "paid",
      "impr": 244345,
      "paidImpr": 244345,
      "orgImpr": 0,
      "eng": 162580,
      "er": 66.54,
      "spend": 1129.99,
      "url": null
    },
    {
      "title": "Mauigoa",
      "platform": "Facebook",
      "distKind": "paid",
      "impr": 236867,
      "paidImpr": 236867,
      "orgImpr": 0,
      "eng": 155026,
      "er": 65.45,
      "spend": 1123.38,
      "url": null
    },
    {
      "title": "Tate",
      "platform": "Facebook",
      "distKind": "paid",
      "impr": 230455,
      "paidImpr": 230455,
      "orgImpr": 0,
      "eng": 156334,
      "er": 67.84,
      "spend": 1129.98,
      "url": null
    },
    {
      "title": "Downs",
      "platform": "Facebook",
      "distKind": "paid",
      "impr": 225505,
      "paidImpr": 225505,
      "orgImpr": 0,
      "eng": 155485,
      "er": 68.95,
      "spend": 1129.98,
      "url": null
    }
  ]
};

window.DATA_ARCHIVE = [
  {
    "campaignId": "usbank",
    "partner": "US Bank",
    "sourceKind": "meta_ads",
    "sourceLabel": "Meta Ads",
    "filename": "usbank_meta_ads.csv",
    "fileSizeKb": 2.2,
    "lastModified": "2026-05-13",
    "exists": true,
    "postsContributed": 10
  }
];

window.BENCHMARKS_DATA = {
  "lastUpdated": "3/5 @1pm EST",
  "platformSummary": [
    {
      "row": "All Content",
      "platforms": {
        "Instagram": 3.6,
        "Facebook": 4.0,
        "X": 2.3,
        "TikTok": 4.9,
        "LinkedIn": 5.2,
        "YouTube": 1.0
      },
      "allAvg": 3.5
    },
    {
      "row": "Sponsored (Sprout, No Paid)",
      "platforms": {
        "Instagram": 3.8,
        "Facebook": 2.6,
        "X": 1.1,
        "TikTok": 0.9,
        "LinkedIn": 2.4,
        "YouTube": 1.0
      },
      "allAvg": 1.97
    },
    {
      "row": "Sponsored (All content in this doc)",
      "platforms": {
        "Instagram": 3.29,
        "Facebook": 1.91,
        "X": 0.88,
        "TikTok": 1.84,
        "LinkedIn": 3.68,
        "YouTube": 3.17
      },
      "allAvg": 2.46
    }
  ],
  "categories": [
    {
      "name": "Social Coverage Partner",
      "overall": {
        "Instagram": 6.82,
        "Facebook": 1.63,
        "X": 1.3,
        "TikTok": 3.29,
        "LinkedIn": 5.56,
        "Shorts": 0.75,
        "All": 4.6
      },
      "campaigns": [
        {
          "name": "Acura x Business of the Madness (2024)",
          "platforms": {
            "Instagram": 11.32,
            "Facebook": 4.34,
            "TikTok": 3.95,
            "LinkedIn": 3.63
          },
          "all": 6.34,
          "spend": ""
        },
        {
          "name": "US Bank x Golf",
          "platforms": {
            "Instagram": 11.52,
            "X": 1.97,
            "TikTok": 4.13,
            "LinkedIn": 4.75
          },
          "all": 6.43,
          "spend": ""
        },
        {
          "name": "Upper Deck x NHL Draft",
          "platforms": {
            "Instagram": 3.06,
            "Facebook": 0.37,
            "X": 0.64,
            "TikTok": 1.8,
            "LinkedIn": 11.08,
            "Shorts": 0.75
          },
          "all": 2.32,
          "spend": ""
        },
        {
          "name": "Invesco QQQ x Busines of Bowl Season",
          "platforms": {
            "Instagram": 4.19,
            "LinkedIn": 4.38
          },
          "all": 4.2,
          "spend": ""
        },
        {
          "name": "US Bank x 2026 NFL Draft",
          "platforms": {
            "Instagram": 4.02,
            "Facebook": 0.19,
            "X": 1.28,
            "LinkedIn": 3.95
          },
          "all": 3.69,
          "spend": ""
        }
      ]
    },
    {
      "name": "Social - IP/Franchise",
      "overall": {
        "Instagram": 4.59,
        "Facebook": 4.22,
        "X": 0.46,
        "TikTok": 4.5,
        "LinkedIn": 3.44,
        "Shorts": null,
        "All": 3.44
      },
      "campaigns": [
        {
          "name": "TickPick x Big Ticket (9/24 - 2/25)",
          "platforms": {
            "Instagram": 7.37,
            "X": 0.81,
            "TikTok": 4.82
          },
          "all": 7.17,
          "spend": ""
        },
        {
          "name": "Daktronics x Stadium Status (12/24 - 4/25)",
          "platforms": {
            "Instagram": 1.46,
            "LinkedIn": 4.38
          },
          "all": 1.56,
          "spend": ""
        },
        {
          "name": "AT&T x Stadium Status",
          "platforms": {
            "Instagram": 1.29,
            "X": 0.45,
            "TikTok": 6.0,
            "LinkedIn": 4.76
          },
          "all": 1.39,
          "spend": ""
        },
        {
          "name": "Gainbridge x The Come Up (Napheesa Collier)",
          "platforms": {
            "Instagram": 3.46,
            "TikTok": 5.31,
            "LinkedIn": 3.26
          },
          "all": 4.85,
          "spend": ""
        },
        {
          "name": "RBC x Second Acts",
          "platforms": {
            "Instagram": 5.68,
            "Facebook": 0.75,
            "LinkedIn": 1.9
          },
          "all": 3.6,
          "spend": ""
        },
        {
          "name": "Dealmaker x Asset Class",
          "platforms": {
            "Instagram": 1.25,
            "Facebook": 0.19,
            "X": 0.32,
            "LinkedIn": 1.22
          },
          "all": null,
          "spend": ""
        },
        {
          "name": "Pepsi x Stadium Eats",
          "platforms": {
            "Instagram": 2.59,
            "Facebook": 1.98,
            "X": 0.24,
            "TikTok": 1.88,
            "LinkedIn": 6.84
          },
          "all": 1.19,
          "spend": ""
        },
        {
          "name": "Toyota x Winter Olympics",
          "platforms": {
            "Instagram": 13.61,
            "Facebook": 13.95,
            "LinkedIn": 1.73
          },
          "all": 13.42,
          "spend": ""
        }
      ]
    },
    {
      "name": "Custom Social",
      "overall": {
        "Instagram": 5.07,
        "Facebook": 4.56,
        "X": 0.91,
        "TikTok": 0.7,
        "LinkedIn": 3.6,
        "Shorts": null,
        "All": 2.97
      },
      "campaigns": [
        {
          "name": "Gainbridge x Parity Week 2024",
          "platforms": {
            "Instagram": 7.47,
            "X": 1.13,
            "LinkedIn": 1.59
          },
          "all": 3.46,
          "spend": ""
        },
        {
          "name": "Laver Cup",
          "platforms": {
            "Instagram": 4.03,
            "Facebook": 0.09,
            "X": 1.26,
            "LinkedIn": 2.79
          },
          "all": 2.45,
          "spend": ""
        },
        {
          "name": "LOVB",
          "platforms": {
            "Instagram": 8.5,
            "X": 0.63,
            "LinkedIn": 4.91
          },
          "all": 6.15,
          "spend": ""
        },
        {
          "name": "Wilson x Super Bowl, ASG, Caitlin Clark",
          "platforms": {
            "Instagram": 1.71,
            "TikTok": 0.13
          },
          "all": 0.89,
          "spend": ""
        },
        {
          "name": "Comcast Business x The Players",
          "platforms": {
            "Instagram": 0.15,
            "LinkedIn": 9.69
          },
          "all": 0.24,
          "spend": ""
        },
        {
          "name": "Champs Sports CSG x Brock Bowers",
          "platforms": {
            "Instagram": 8.95,
            "X": 0.37,
            "TikTok": 0.06,
            "LinkedIn": 2.45
          },
          "all": 3.27,
          "spend": ""
        },
        {
          "name": "Atlassian x Australian Grand Prix",
          "platforms": {
            "Instagram": 0.29,
            "X": 0.43,
            "LinkedIn": 2.05
          },
          "all": 0.33,
          "spend": ""
        },
        {
          "name": "Champs x Fall Football",
          "platforms": {
            "Instagram": 3.06,
            "TikTok": 0.54
          },
          "all": 1.76,
          "spend": ""
        },
        {
          "name": "Nuveen x Bobby Bonilla",
          "platforms": {
            "Instagram": 11.09,
            "X": 1.72,
            "LinkedIn": 2.26
          },
          "all": 5.14,
          "spend": ""
        },
        {
          "name": "Gatorade x Modern Origins",
          "platforms": {
            "Instagram": 3.18,
            "TikTok": 0.25,
            "LinkedIn": 2.77
          },
          "all": 1.94,
          "spend": ""
        },
        {
          "name": "Gainbridge x WNBA All-Star",
          "platforms": {
            "Instagram": 8.88,
            "Facebook": 15.69,
            "TikTok": 3.08,
            "LinkedIn": 4.92
          },
          "all": 11.43,
          "spend": ""
        },
        {
          "name": "Tissot x NBA",
          "platforms": {
            "Instagram": 6.56
          },
          "all": 6.56,
          "spend": ""
        },
        {
          "name": "Healthy Paws x Globetrotting",
          "platforms": {
            "Instagram": 3.89,
            "Facebook": 0.26,
            "X": 1.46
          },
          "all": 2.28,
          "spend": ""
        },
        {
          "name": "Professional Fighters League",
          "platforms": {
            "Instagram": 3.21,
            "Facebook": 2.19,
            "X": 0.27,
            "TikTok": 0.14,
            "LinkedIn": 2.56
          },
          "all": 1.2,
          "spend": ""
        }
      ]
    },
    {
      "name": "Multimedia Reporter-Led - IP/Franchise",
      "overall": {
        "Instagram": 3.0,
        "Facebook": 1.65,
        "X": 0.39,
        "TikTok": 1.94,
        "LinkedIn": 3.75,
        "Shorts": 2.73,
        "All": 2.24
      },
      "campaigns": [
        {
          "name": "Kaiser Permanante x Stadium Status",
          "platforms": {
            "Instagram": 1.16,
            "X": 0.66,
            "TikTok": 0.07,
            "LinkedIn": 4.99,
            "Shorts": 5.16
          },
          "all": 0.54,
          "spend": ""
        },
        {
          "name": "Daktronics x Stadium Status (Lindsay)",
          "platforms": {
            "Instagram": 1.64,
            "TikTok": 1.64,
            "LinkedIn": 0.99
          },
          "all": 1.05,
          "spend": ""
        },
        {
          "name": "AT&T x Stadium Status (Intuit Dome)",
          "platforms": {
            "Instagram": 1.29,
            "X": 0.45,
            "TikTok": 6.0,
            "LinkedIn": 4.76
          },
          "all": 1.39,
          "spend": ""
        },
        {
          "name": "Fanatics x Stadium Status",
          "platforms": {},
          "all": null,
          "spend": ""
        },
        {
          "name": "Elevate Stadium Status",
          "platforms": {
            "Instagram": 3.18,
            "X": 0.06,
            "TikTok": 0.06,
            "LinkedIn": 4.26,
            "Shorts": 0.29
          },
          "all": 0.96,
          "spend": ""
        },
        {
          "name": "US Bank x The Come Up",
          "platforms": {
            "Instagram": 7.75,
            "Facebook": 1.65,
            "X": 0.1,
            "LinkedIn": 3.32,
            "Shorts": 25.5
          },
          "all": 7.18,
          "spend": ""
        }
      ]
    },
    {
      "name": "Custom Multimedia Reporter-Led (Tentpole Event, Custom Series, etc.)",
      "overall": {
        "Instagram": 2.31,
        "Facebook": 0.0,
        "X": 0.37,
        "TikTok": 0.45,
        "LinkedIn": 2.98,
        "Shorts": 3.97,
        "All": 1.68
      },
      "campaigns": [
        {
          "name": "Gainbridge x Parity Week (2024) (Lindsay)",
          "platforms": {
            "Instagram": 5.02,
            "X": 0.35,
            "TikTok": 0.12
          },
          "all": 1.64,
          "spend": ""
        },
        {
          "name": "EA Sports x College Football (Lindsay & Derryl)",
          "platforms": {
            "Instagram": 1.01,
            "X": 1.01,
            "TikTok": 0.32
          },
          "all": 0.69,
          "spend": ""
        },
        {
          "name": "AWS x NFL Women's Forum (Lindsay)",
          "platforms": {
            "Instagram": 0.11,
            "X": 0.3,
            "TikTok": 0.03,
            "LinkedIn": 3.95
          },
          "all": 0.15,
          "spend": ""
        },
        {
          "name": "Invesco x Under Review (Lindsay)",
          "platforms": {
            "Instagram": 2.51,
            "TikTok": 0.05,
            "Shorts": 2.69
          },
          "all": 1.23,
          "spend": ""
        },
        {
          "name": "Champs Sports x Apparel Playmakers (Derryl)",
          "platforms": {
            "Instagram": 1.5,
            "TikTok": 0.38
          },
          "all": 0.96,
          "spend": ""
        },
        {
          "name": "Tissot x NBA (Derryl)",
          "platforms": {
            "Instagram": 1.06,
            "X": 0.3,
            "TikTok": 0.03,
            "LinkedIn": 3.47
          },
          "all": 0.48,
          "spend": ""
        },
        {
          "name": "US Bank x PLL Championship",
          "platforms": {
            "Instagram": 3.35,
            "X": 0.31,
            "TikTok": 0.4,
            "Shorts": 9.1
          },
          "all": 3.3,
          "spend": ""
        },
        {
          "name": "PGA Tour x BMW Championship (Derryl)",
          "platforms": {
            "Instagram": 1.63,
            "TikTok": 2.75
          },
          "all": 2.37,
          "spend": ""
        },
        {
          "name": "Gainbridge x WNBA All-Star (Lindsay)",
          "platforms": {
            "Instagram": 4.75,
            "X": 0.24,
            "TikTok": 0.29,
            "LinkedIn": 1.53
          },
          "all": 1.74,
          "spend": ""
        },
        {
          "name": "Swag Golf x Ryder Cup",
          "platforms": {
            "Instagram": 2.15,
            "X": 0.11,
            "TikTok": 0.1,
            "Shorts": 0.12
          },
          "all": 0.5,
          "spend": ""
        },
        {
          "name": "Laver Cup",
          "platforms": {
            "Instagram": 0.3,
            "X": 7.37,
            "TikTok": 3.24,
            "LinkedIn": 1.07
          },
          "all": 5.45,
          "spend": ""
        },
        {
          "name": "Gainbridge Parity Week (2025)",
          "platforms": {},
          "all": null,
          "spend": ""
        }
      ]
    },
    {
      "name": "Creator-Led - IP/Franchise",
      "overall": {
        "Instagram": 3.8,
        "Facebook": 5.19,
        "X": null,
        "TikTok": 0.51,
        "LinkedIn": null,
        "Shorts": null,
        "All": 1.58
      },
      "campaigns": [
        {
          "name": "DIRECTV x The Come Up",
          "platforms": {
            "Instagram": 3.8,
            "Facebook": 5.19,
            "TikTok": 0.51
          },
          "all": 1.58,
          "spend": ""
        }
      ]
    },
    {
      "name": "Custom Creator-Led",
      "overall": {
        "Instagram": 3.91,
        "Facebook": 0.14,
        "X": 0.45,
        "TikTok": 1.31,
        "LinkedIn": 4.58,
        "Shorts": 4.67,
        "All": 2.51
      },
      "campaigns": [
        {
          "name": "Invesco x Under Review 2023 (Breneman CFB)",
          "platforms": {
            "Instagram": 5.62,
            "TikTok": 2.84,
            "LinkedIn": 3.25,
            "Shorts": 1.96
          },
          "all": 7.0,
          "spend": ""
        },
        {
          "name": "Invesco x Under Review 2024 (Jordan Rogers MM)",
          "platforms": {
            "Instagram": 0.59,
            "TikTok": 1.08,
            "Shorts": 2.23
          },
          "all": 0.72,
          "spend": ""
        },
        {
          "name": "Champs x Off the Pitch (Eli Lesser)",
          "platforms": {
            "Instagram": 1.3,
            "TikTok": 7.2,
            "Shorts": 3.83
          },
          "all": 3.37,
          "spend": ""
        },
        {
          "name": "Gainbridge x Parity Week (2024)",
          "platforms": {
            "Instagram": 5.16,
            "X": 0.43,
            "TikTok": 0.11
          },
          "all": 1.19,
          "spend": ""
        },
        {
          "name": "Invesco x Under Review 2024 (Breneman CFB)",
          "platforms": {
            "Instagram": 1.76,
            "TikTok": 0.2,
            "LinkedIn": 0.4
          },
          "all": 0.89,
          "spend": ""
        },
        {
          "name": "Comcast Business x PLAYERS (Bradford Wilson)",
          "platforms": {
            "Instagram": 12.2,
            "X": 0.29,
            "TikTok": 0.02,
            "LinkedIn": 10.09
          },
          "all": 2.74,
          "spend": ""
        },
        {
          "name": "Johnnie O x Under Review 2025 (Breneman CFB)",
          "platforms": {
            "Instagram": 6.57,
            "X": 0.18,
            "TikTok": 0.22,
            "Shorts": 0.94
          },
          "all": 1.46,
          "spend": ""
        },
        {
          "name": "Comcast x PLAYERS 2026 (Lauren & Bailey)",
          "platforms": {
            "Instagram": 0.88,
            "Facebook": 0.05,
            "TikTok": 0.04,
            "Shorts": 6.15
          },
          "all": 2.12,
          "spend": ""
        },
        {
          "name": "US Bank x 2026 Super Bowl Activation",
          "platforms": {
            "Instagram": 1.11,
            "Facebook": 0.24,
            "X": 0.88,
            "TikTok": 0.05,
            "Shorts": 12.88
          },
          "all": 0.75,
          "spend": ""
        }
      ]
    },
    {
      "name": "Shows (Cutdowns & Custom Integrations)",
      "overall": {
        "YouTube": 2.8,
        "Instagram": 1.44,
        "Facebook": 0.0,
        "X": 0.32,
        "TikTok": 2.16,
        "LinkedIn": null,
        "Shorts": 1.38
      },
      "campaigns": [
        {
          "name": "LYCRA x Redefined",
          "platforms": {
            "YouTube": 1.74,
            "Instagram": 0.58,
            "Facebook": 0.0,
            "TikTok": 7.65,
            "Shorts": 1.38
          },
          "all": 1.37,
          "spend": ""
        },
        {
          "name": "Nike x NILOSOPHY",
          "platforms": {
            "Instagram": 1.85,
            "TikTok": 0.08
          },
          "all": 0.92,
          "spend": ""
        },
        {
          "name": "OLIPOP x NILOSOPHY",
          "platforms": {
            "YouTube": 3.87,
            "Instagram": 2.23,
            "TikTok": 0.86
          },
          "all": 2.96,
          "spend": ""
        },
        {
          "name": "RBC House x Redefined",
          "platforms": {
            "Instagram": 1.1,
            "TikTok": 0.05
          },
          "all": 0.48,
          "spend": ""
        },
        {
          "name": "RBC House x FOS Today",
          "platforms": {
            "X": 0.32
          },
          "all": 0.32,
          "spend": ""
        }
      ]
    },
    {
      "name": "Original Content",
      "overall": {
        "YouTube": 1.61,
        "Instagram": 2.32,
        "Facebook": 0.89,
        "X": 1.56,
        "TikTok": 0.97,
        "LinkedIn": 3.57,
        "Shorts": 6.42
      },
      "campaigns": [
        {
          "name": "Gatorade x FOS Explains: Women Fueling Football",
          "platforms": {
            "YouTube": 1.62,
            "Instagram": 2.04,
            "X": 9.08,
            "TikTok": 2.18,
            "LinkedIn": 2.7
          },
          "all": 2.75,
          "spend": ""
        },
        {
          "name": "Wilson x FOS Explains",
          "platforms": {
            "YouTube": 2.41,
            "Instagram": 0.77,
            "X": 0.24,
            "TikTok": 0.03,
            "LinkedIn": 2.43
          },
          "all": 1.17,
          "spend": ""
        },
        {
          "name": "FOS Explains x PGA Tour",
          "platforms": {
            "YouTube": 1.79,
            "Instagram": 6.25,
            "X": 0.24,
            "TikTok": 0.07,
            "LinkedIn": 4.32
          },
          "all": 1.56,
          "spend": ""
        },
        {
          "name": "E*TRADE x Portfolio Players (Season 1)",
          "platforms": {
            "YouTube": 1.5,
            "Instagram": 2.39,
            "Facebook": 0.09,
            "X": 0.59,
            "TikTok": 0.07,
            "LinkedIn": 1.33
          },
          "all": 1.2,
          "spend": ""
        },
        {
          "name": "Pepsi x Stadium Eats",
          "platforms": {
            "YouTube": 1.01,
            "Instagram": 2.59,
            "Facebook": 1.98,
            "X": 0.24,
            "TikTok": 1.88,
            "LinkedIn": 6.84
          },
          "all": 1.19,
          "spend": ""
        },
        {
          "name": "E*TRADE x Portfolio Players (Season 2)",
          "platforms": {
            "YouTube": 1.32,
            "Instagram": 1.61,
            "Facebook": 0.61,
            "X": 0.25,
            "TikTok": 2.51,
            "LinkedIn": 3.07,
            "Shorts": 7.42
          },
          "all": 1.42,
          "spend": ""
        },
        {
          "name": "Bet MGM FOS Explains - Winter Olympics",
          "platforms": {
            "YouTube": 1.63,
            "Instagram": 0.59,
            "X": 0.28,
            "TikTok": 0.05,
            "LinkedIn": 4.27,
            "Shorts": 5.43
          },
          "all": 1.32,
          "spend": ""
        }
      ]
    },
    {
      "name": "Branded Content",
      "overall": {
        "YouTube": 3.17,
        "Instagram": 2.58,
        "Facebook": 0.25,
        "X": 2.79,
        "TikTok": 0.94,
        "LinkedIn": 3.47,
        "Shorts": 2.46
      },
      "campaigns": [
        {
          "name": "Rocket Mortgage x A Dreammate Story",
          "platforms": {
            "YouTube": 2.1,
            "Instagram": 0.82,
            "Facebook": 0.61,
            "TikTok": 1.25,
            "LinkedIn": 2.86,
            "Shorts": 2.42
          },
          "all": 2.23,
          "spend": ""
        },
        {
          "name": "Dick's Sporting Goods x Boston Bound",
          "platforms": {
            "YouTube": 4.79,
            "Instagram": 0.37,
            "X": 4.58,
            "TikTok": 1.46,
            "LinkedIn": 3.01,
            "Shorts": 3.54
          },
          "all": 3.18,
          "spend": ""
        },
        {
          "name": "Upper Deck x Athlete Archives",
          "platforms": {
            "YouTube": 3.46,
            "Instagram": 2.29,
            "Facebook": 0.2,
            "X": 4.15,
            "TikTok": 1.13,
            "LinkedIn": 3.5,
            "Shorts": 3.88
          },
          "all": 3.26,
          "spend": ""
        },
        {
          "name": "US Bank x Untold Team",
          "platforms": {
            "YouTube": 2.16,
            "Instagram": 4.18,
            "Facebook": 0.16,
            "X": 5.68,
            "LinkedIn": 3.31
          },
          "all": 3.41,
          "spend": ""
        },
        {
          "name": "Wells Fargo x Breaking Barriers",
          "platforms": {
            "YouTube": 7.32,
            "Instagram": 2.84,
            "TikTok": 0.17,
            "LinkedIn": 3.18,
            "Shorts": 0.06
          },
          "all": 0.62,
          "spend": ""
        },
        {
          "name": "LYCRA x Redefined Launch",
          "platforms": {
            "YouTube": 2.14,
            "Instagram": 3.12,
            "X": 1.29,
            "TikTok": 2.23,
            "LinkedIn": 4.39,
            "Shorts": 2.39
          },
          "all": 2.45,
          "spend": ""
        },
        {
          "name": "Nuveen x The Big Deal (Bobby Bonilla)",
          "platforms": {
            "YouTube": 2.03,
            "Instagram": 3.45,
            "X": 0.69,
            "TikTok": 0.25,
            "LinkedIn": 3.55
          },
          "all": 1.65,
          "spend": ""
        },
        {
          "name": "Gainbridge x USL",
          "platforms": {
            "YouTube": 1.35,
            "Instagram": 3.58,
            "Facebook": 0.04,
            "X": 0.36,
            "TikTok": 0.06,
            "LinkedIn": 3.94
          },
          "all": 1.05,
          "spend": ""
        },
        {
          "name": "State Farm the Family Assist",
          "platforms": {
            "YouTube": 3.14,
            "Instagram": 2.7,
            "X": 0.03,
            "TikTok": 0.15,
            "LinkedIn": 3.77
          },
          "all": 1.8,
          "spend": ""
        }
      ]
    },
    {
      "name": "FOS Event - Custom Social",
      "overall": {
        "Instagram": 1.67,
        "Facebook": 4.29,
        "X": 0.5,
        "TikTok": 0.15,
        "LinkedIn": 3.46,
        "Shorts": 4.86,
        "All": 1.92
      },
      "campaigns": [
        {
          "name": "Raising Cane's x The Breakfast Ball 2025",
          "platforms": {},
          "all": null,
          "spend": ""
        },
        {
          "name": "Polestar x The Breakfast Ball 2025",
          "platforms": {
            "Instagram": 0.81,
            "X": 0.2,
            "TikTok": 0.02,
            "LinkedIn": 3.64
          },
          "all": 0.42,
          "spend": ""
        },
        {
          "name": "AG1 x The Breakfast Ball 2025",
          "platforms": {
            "Instagram": 1.1,
            "Facebook": 7.93,
            "X": 1.28,
            "TikTok": 0.05,
            "LinkedIn": 1.39,
            "Shorts": 1.36
          },
          "all": 2.15,
          "spend": ""
        },
        {
          "name": "Tommy John x The Breakfast Ball 2025",
          "platforms": {
            "Instagram": 0.19,
            "X": 0.13,
            "TikTok": 0.06,
            "LinkedIn": 4.1
          },
          "all": 0.16,
          "spend": ""
        },
        {
          "name": "RBC House",
          "platforms": {
            "Instagram": 2.67,
            "Facebook": 0.65,
            "LinkedIn": 3.44
          },
          "all": 1.44,
          "spend": ""
        },
        {
          "name": "Eli Lilly x Courtside Collective",
          "platforms": {
            "Instagram": 1.85,
            "TikTok": 0.04
          },
          "all": 1.0,
          "spend": ""
        },
        {
          "name": "Second Acts Live (Sue Bird) x Ally",
          "platforms": {
            "Instagram": 1.98,
            "X": 0.38,
            "TikTok": 0.77,
            "Shorts": 0.15
          },
          "all": 0.68,
          "spend": ""
        },
        {
          "name": "Thomas's Bagels x The Breakfast Ball 2026",
          "platforms": {
            "Instagram": 3.5,
            "TikTok": 0.05,
            "Shorts": 11.82
          },
          "all": 6.33,
          "spend": ""
        },
        {
          "name": "Raising Cane's x The Breakfast Ball 2026",
          "platforms": {
            "Instagram": 1.29,
            "TikTok": 0.03,
            "LinkedIn": 4.72,
            "Shorts": 6.09
          },
          "all": 3.15,
          "spend": ""
        }
      ]
    },
    {
      "name": "FOS Event - Presenting Partner",
      "overall": {
        "Instagram": 1.92,
        "Facebook": 0.1,
        "X": 0.6,
        "TikTok": 5.13,
        "LinkedIn": 2.4,
        "Shorts": null,
        "All": 2.03
      },
      "campaigns": [
        {
          "name": "Elevate x Tuned In",
          "platforms": {
            "Instagram": 2.58,
            "Facebook": 0.0,
            "X": 0.88,
            "TikTok": 5.13,
            "LinkedIn": 3.59
          },
          "all": 2.85,
          "spend": ""
        },
        {
          "name": "Dealmaker x Asset Class",
          "platforms": {
            "Instagram": 1.25,
            "Facebook": 0.19,
            "X": 0.32,
            "LinkedIn": 1.22
          },
          "all": 0.68,
          "spend": ""
        }
      ]
    }
  ]
};



window.fmt = {
  num(n) {
    if (n >= 1_000_000) return (n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1) + 'M';
    if (n >= 1_000) return (n / 1_000).toFixed(n >= 10_000 ? 0 : 1) + 'K';
    return n.toString();
  },
  // Full integer with thousands separators (no K/M abbreviation).
  numFull(n) { return Math.round(Number(n) || 0).toLocaleString('en-US'); },
  pct(n, d = 1) { return n.toFixed(d) + '%'; },
  money(n) {
    if (n >= 1_000) return '$' + (n / 1_000).toFixed(1) + 'K';
    // Sub-thousand: whole dollars, no cents. Cents on spend add no useful info.
    return '$' + Math.round(n).toLocaleString();
  },
  // Full dollar amount with cents (e.g. $1,497.32). Used in episode breakdowns
  // where precise per-platform spend matters.
  moneyFull(n) {
    const v = Number(n) || 0;
    return '$' + v.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
};

